name: Docker

on: push
  

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}


jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Create docker image
        run: docker build -t cypress-tests .

      - name: Run Cypress tests
        run: docker run --rm -v $(pwd)/cypress/results:/app/cypress/results cypress-tests

      - name: Upload test results
        uses: actions/upload-artifact@v3
        with:
          name: cypress-results
          path: cypress/results
